import { normalize, tokenize } from "./normalize";
const data = [
  {
    slug: "dior-sauvage",
    name: "ساواژ",
    brand: "دیور",
    gender: "men",
    releaseYear: 2015,
    concentration: "EDT",
    priceRange: "mid",
    longevity: 4,
    projection: 4,
    sweetness: 2,
    freshness: 4,
    seasons: ["spring", "summer", "autumn"],
    occasions: ["daily", "casual"],
    scentFamilies: ["fresh", "spicy", "aromatic"],
    notes: {
      top: ["برگاموت", "فلفل"],
      middle: ["فلفل سچوان", "اسطوخودوس"],
      base: ["آمبروکسان", "سدر"],
    },
    description: "عطری جسور، تازه و ادویه‌ای با پایه برگاموت و آمبروکسان.",
  },
  {
    slug: "creed-aventus",
    name: "اونتوس",
    brand: "کرید",
    gender: "men",
    releaseYear: 2010,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 4,
    projection: 4,
    sweetness: 3,
    freshness: 3,
    seasons: ["spring", "summer", "autumn"],
    occasions: ["office", "evening"],
    scentFamilies: ["fruity", "smoky", "woody"],
    notes: {
      top: ["آناناس", "برگاموت", "سیب"],
      middle: ["غان", "پچولی"],
      base: ["مشک", "خزه بلوط", "عنبر"],
    },
    description: "کلاسیک میوه‌ای و دودی با شروعی پرانرژی از آناناس.",
  },
  {
    slug: "pdm-percival",
    name: "پرسیوال",
    brand: "پارفومز دو مارلی",
    gender: "men",
    releaseYear: 2019,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 4,
    projection: 4,
    sweetness: 2,
    freshness: 4,
    seasons: ["spring", "summer"],
    occasions: ["daily", "office"],
    scentFamilies: ["fresh", "aromatic", "citrus"],
    notes: {
      top: ["برگاموت", "لیمو"],
      middle: ["اسطوخودوس", "شمعدانی"],
      base: ["مشک", "سدر"],
    },
    description: "عطری معطر و تازه با حسی تمیز و شسته‌رفته.",
  },
  {
    slug: "kilian-angels-share",
    name: "انجلز شر",
    brand: "کیلیان",
    gender: "unisex",
    releaseYear: 2020,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 5,
    projection: 4,
    sweetness: 5,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "date"],
    scentFamilies: ["gourmand", "woody", "warm-spicy"],
    notes: {
      top: ["کنیاک", "دارچین"],
      middle: ["لوبیا تونکا", "بلوط"],
      base: ["وانیل", "پرالین", "صندل"],
    },
    description:
      "عطری غنی و الکلی با الهام از کهنه‌شدن کنیاک در بشکه‌های بلوط.",
  },
  {
    slug: "ysl-black-opium",
    name: "بلک اپیوم",
    brand: "ایو سن لوران",
    gender: "women",
    releaseYear: 2014,
    concentration: "EDP",
    priceRange: "mid",
    longevity: 4,
    projection: 4,
    sweetness: 5,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "date"],
    scentFamilies: ["gourmand", "coffee", "vanilla"],
    notes: {
      top: ["فلفل صورتی", "گلابی"],
      middle: ["قهوه", "یاس"],
      base: ["وانیل", "پچولی", "سدر"],
    },
    description: "عطری شیرین و اعتیادآور با ترکیب قهوه و وانیل برای شب.",
  },
  {
    slug: "pdm-althair",
    name: "آلتایر",
    brand: "پارفومز دو مارلی",
    gender: "men",
    releaseYear: 2016,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 4,
    projection: 3,
    sweetness: 5,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "date"],
    scentFamilies: ["vanilla", "gourmand", "warm-spicy"],
    notes: {
      top: ["دارچین", "برگاموت"],
      middle: ["پرالین", "شکوفه پرتقال"],
      base: ["وانیل", "لوبیا تونکا", "مشک"],
    },
    description: "وانیلی نرم و کرمی با ادویه گرم و شیرینی لطیف.",
  },
  {
    slug: "chanel-bleu-de-chanel",
    name: "بلو دو شنل",
    brand: "شنل",
    gender: "men",
    releaseYear: 2014,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 4,
    projection: 3,
    sweetness: 2,
    freshness: 4,
    seasons: ["spring", "summer", "autumn"],
    occasions: ["office", "daily"],
    scentFamilies: ["woody", "aromatic", "citrus"],
    notes: {
      top: ["گریپ‌فروت", "لیمو", "نعنا"],
      middle: ["زنجبیل", "جوز هندی", "یاس"],
      base: ["صندل", "سدر", "پچولی"],
    },
    description: "چوبی و مرکباتی با ظاهری مرتب و مناسب هر موقعیت رسمی.",
  },
  {
    slug: "armani-acqua-di-gio-profumo",
    name: "آکوا دی جیو پروفومو",
    brand: "جورجیو آرمانی",
    gender: "men",
    releaseYear: 2015,
    concentration: "Parfum",
    priceRange: "mid",
    longevity: 4,
    projection: 3,
    sweetness: 2,
    freshness: 4,
    seasons: ["spring", "summer"],
    occasions: ["daily", "office"],
    scentFamilies: ["aquatic", "aromatic", "woody"],
    notes: {
      top: ["برگاموت", "نت دریایی"],
      middle: ["اسطوخودوس", "مریم‌گلی", "رزماری"],
      base: ["پچولی", "بخور"],
    },
    description: "دریایی و معطر با لایه‌ای دودی و عمیق‌تر از نسخه اصلی.",
  },
  {
    slug: "versace-eros",
    name: "اروس",
    brand: "ورساچه",
    gender: "men",
    releaseYear: 2012,
    concentration: "EDT",
    priceRange: "mid",
    longevity: 4,
    projection: 4,
    sweetness: 4,
    freshness: 4,
    seasons: ["spring", "summer"],
    occasions: ["casual", "evening"],
    scentFamilies: ["fresh", "vanilla", "fruity"],
    notes: {
      top: ["نعنا", "سیب سبز", "لیمو"],
      middle: ["لوبیا تونکا", "ژرانیوم"],
      base: ["وانیل", "سدر", "خزه بلوط"],
    },
    description: "ترکیب پرانرژی نعنا و وانیل، شیرین و خنک در کنار هم.",
  },
  {
    slug: "tom-ford-oud-wood",
    name: "عود وود",
    brand: "تام فورد",
    gender: "unisex",
    releaseYear: 2007,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 4,
    projection: 3,
    sweetness: 2,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "office"],
    scentFamilies: ["oud", "woody", "warm-spicy"],
    notes: {
      top: ["هل", "چوب رزوود"],
      middle: ["عود", "صندل", "چوب‌ها"],
      base: ["وانیل", "عنبر", "تونکا"],
    },
    description:
      "عودی نرم و صیقل‌خورده، مناسب کسانی که اولین بار سراغ عود می‌روند.",
  },
  {
    slug: "tom-ford-tobacco-vanille",
    name: "توباکو وانیل",
    brand: "تام فورد",
    gender: "unisex",
    releaseYear: 2007,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 5,
    projection: 4,
    sweetness: 4,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "date"],
    scentFamilies: ["gourmand", "vanilla", "warm-spicy"],
    notes: {
      top: ["برگ تنباکو", "ادویه"],
      middle: ["وانیل", "کاکائو", "گل تنباکو"],
      base: ["میوه خشک", "چوب"],
    },
    description: "تنباکو و وانیلی گرم و غلیظ، انتخابی برای شب‌های سرد.",
  },
  {
    slug: "chanel-coco-mademoiselle",
    name: "کوکو مادمازل",
    brand: "شنل",
    gender: "women",
    releaseYear: 2001,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 4,
    projection: 4,
    sweetness: 3,
    freshness: 3,
    seasons: ["spring", "autumn"],
    occasions: ["office", "date"],
    scentFamilies: ["floral", "citrus", "woody"],
    notes: {
      top: ["پرتقال", "برگاموت"],
      middle: ["گل رز", "یاس"],
      base: ["پچولی", "وتیور", "مشک سفید"],
    },
    description: "گلی و مرکباتی با پایه‌ای پچولی، کلاسیک و همیشه مدرن.",
  },
  {
    slug: "chanel-no5",
    name: "نامبر ۵",
    brand: "شنل",
    gender: "women",
    releaseYear: 1921,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 4,
    projection: 3,
    sweetness: 2,
    freshness: 2,
    seasons: ["spring", "autumn", "winter"],
    occasions: ["evening", "office"],
    scentFamilies: ["floral", "powdery"],
    notes: {
      top: ["آلدهید", "ایلنگ‌ایلنگ", "نرولی"],
      middle: ["یاس", "رز", "زنبق"],
      base: ["وانیل", "صندل", "وتیور"],
    },
    description: "گل‌های پودری و آلدهیدی، نماد کلاسیک عطر زنانه.",
  },
  {
    slug: "lancome-la-vie-est-belle",
    name: "لا ویه است بل",
    brand: "لانکوم",
    gender: "women",
    releaseYear: 2012,
    concentration: "EDP",
    priceRange: "mid",
    longevity: 4,
    projection: 4,
    sweetness: 5,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["date", "evening"],
    scentFamilies: ["gourmand", "floral", "vanilla"],
    notes: {
      top: ["گلابی", "قره‌قاط"],
      middle: ["زنبق", "یاس", "گل پرتقال"],
      base: ["پرالین", "وانیل", "پچولی"],
    },
    description: "شیرین و گلی با زنبق و پرالین، محبوب و دلنشین.",
  },
  {
    slug: "ysl-libre",
    name: "لیبره",
    brand: "ایو سن لوران",
    gender: "women",
    releaseYear: 2019,
    concentration: "EDP",
    priceRange: "mid",
    longevity: 4,
    projection: 4,
    sweetness: 3,
    freshness: 3,
    seasons: ["spring", "autumn"],
    occasions: ["daily", "office", "date"],
    scentFamilies: ["floral", "aromatic", "vanilla"],
    notes: {
      top: ["اسطوخودوس", "ماندارین", "گل‌ سیاه‌دانه"],
      middle: ["یاس", "گل پرتقال"],
      base: ["وانیل", "مشک", "عنبر"],
    },
    description: "ترکیب جسورانه اسطوخودوس و گل پرتقال با پایه وانیلی.",
  },
  {
    slug: "dior-jadore",
    name: "جادور",
    brand: "دیور",
    gender: "women",
    releaseYear: 1999,
    concentration: "EDP",
    priceRange: "mid",
    longevity: 3,
    projection: 3,
    sweetness: 3,
    freshness: 3,
    seasons: ["spring", "summer"],
    occasions: ["daily", "office"],
    scentFamilies: ["floral", "fruity"],
    notes: {
      top: ["گلابی", "ماندارین"],
      middle: ["یاس", "رز", "ایلنگ‌ایلنگ"],
      base: ["مشک", "سدر", "وانیل"],
    },
    description: "دسته‌گلی روشن و میوه‌ای، ظریف و دوست‌داشتنی.",
  },
  {
    slug: "dior-homme-intense",
    name: "دیور هوم اینتنس",
    brand: "دیور",
    gender: "men",
    releaseYear: 2011,
    concentration: "EDP",
    priceRange: "mid",
    longevity: 4,
    projection: 3,
    sweetness: 3,
    freshness: 2,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "date"],
    scentFamilies: ["powdery", "woody", "floral"],
    notes: {
      top: ["لاوندر", "گلابی"],
      middle: ["زنبق (آیریس)", "کاکائو"],
      base: ["وتیور", "چرم", "عنبر"],
    },
    description: "پودری و ظریف با آیریس و کاکائو، شیک و دلنشین.",
  },
  {
    slug: "jpg-le-male",
    name: "لو ماله",
    brand: "ژان پل گوتیه",
    gender: "men",
    releaseYear: 1995,
    concentration: "EDT",
    priceRange: "mid",
    longevity: 3,
    projection: 4,
    sweetness: 4,
    freshness: 3,
    seasons: ["spring", "autumn", "winter"],
    occasions: ["casual", "date"],
    scentFamilies: ["aromatic", "vanilla", "spicy"],
    notes: {
      top: ["نعنا", "اسطوخودوس", "برگاموت"],
      middle: ["دارچین", "هل", "گل پرتقال"],
      base: ["وانیل", "تونکا", "عنبر"],
    },
    description: "کلاسیک اسطوخودوس و وانیل که دهه‌هاست محبوب مانده.",
  },
  {
    slug: "paco-rabanne-1-million",
    name: "وان میلیون",
    brand: "پاکو رابان",
    gender: "men",
    releaseYear: 2008,
    concentration: "EDT",
    priceRange: "mid",
    longevity: 4,
    projection: 5,
    sweetness: 5,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "casual"],
    scentFamilies: ["spicy", "gourmand", "leather"],
    notes: {
      top: ["گریپ‌فروت", "نعنا", "مندرین"],
      middle: ["دارچین", "رز", "ادویه"],
      base: ["چرم", "عنبر", "پچولی"],
    },
    description: "شیرین، تند و پرجلوه با پخش بوی بالا.",
  },
  {
    slug: "paco-rabanne-invictus",
    name: "اینویکتوس",
    brand: "پاکو رابان",
    gender: "men",
    releaseYear: 2013,
    concentration: "EDT",
    priceRange: "mid",
    longevity: 3,
    projection: 4,
    sweetness: 3,
    freshness: 5,
    seasons: ["spring", "summer"],
    occasions: ["casual", "daily"],
    scentFamilies: ["aquatic", "fresh", "woody"],
    notes: {
      top: ["گریپ‌فروت", "نت دریایی", "برگ بو"],
      middle: ["گل یاس", "برگ بو"],
      base: ["چوب گایاک", "عنبر", "پچولی"],
    },
    description: "انرژی‌بخش و دریایی، مناسب روزهای گرم.",
  },
  {
    slug: "armani-stronger-with-you",
    name: "استرانگر ویز یو",
    brand: "جورجیو آرمانی",
    gender: "men",
    releaseYear: 2017,
    concentration: "EDT",
    priceRange: "mid",
    longevity: 4,
    projection: 3,
    sweetness: 4,
    freshness: 2,
    seasons: ["autumn", "winter"],
    occasions: ["date", "casual"],
    scentFamilies: ["warm-spicy", "gourmand", "vanilla"],
    notes: {
      top: ["هل", "فلفل صورتی", "ماندارین"],
      middle: ["بادیان", "مریم‌گلی", "نعنا"],
      base: ["شاه‌بلوط", "وانیل", "چوب"],
    },
    description: "شیرین و گرم با شاه‌بلوط و وانیل، دلپذیر و صمیمی.",
  },
  {
    slug: "montblanc-explorer",
    name: "اکسپلورر",
    brand: "مون بلان",
    gender: "men",
    releaseYear: 2019,
    concentration: "EDP",
    priceRange: "mid",
    longevity: 4,
    projection: 3,
    sweetness: 2,
    freshness: 3,
    seasons: ["spring", "summer", "autumn"],
    occasions: ["daily", "office"],
    scentFamilies: ["woody", "aromatic", "citrus"],
    notes: {
      top: ["برگاموت", "فلفل"],
      middle: ["وتیور", "ریشه ایریس"],
      base: ["پچولی", "چوب گایاک", "امبروکسان"],
    },
    description: "چوبی و معطر با قیمتی منطقی، گزینه‌ای همه‌کاره.",
  },
  {
    slug: "mfk-baccarat-rouge-540",
    name: "باکارا روژ ۵۴۰",
    brand: "مزون فرانسیس کورکجان",
    gender: "unisex",
    releaseYear: 2015,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 5,
    projection: 5,
    sweetness: 4,
    freshness: 2,
    seasons: ["autumn", "winter", "spring"],
    occasions: ["evening", "date"],
    scentFamilies: ["amber", "floral", "woody"],
    notes: {
      top: ["زعفران", "یاس"],
      middle: ["عنبر", "چوب سدر"],
      base: ["صمغ‌ها", "شیره صنوبر"],
    },
    description: "عنبری و ملایم با درخشش شیرین؛ از معروف‌ترین عطرهای دهه اخیر.",
  },
  {
    slug: "byredo-gypsy-water",
    name: "جیپسی واتر",
    brand: "بایردو",
    gender: "unisex",
    releaseYear: 2008,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 3,
    projection: 3,
    sweetness: 2,
    freshness: 3,
    seasons: ["spring", "autumn"],
    occasions: ["daily", "casual"],
    scentFamilies: ["woody", "aromatic", "vanilla"],
    notes: {
      top: ["لیمو", "فلفل", "سوزن کاج"],
      middle: ["بخور", "زنبق"],
      base: ["صندل", "وانیل", "عنبر"],
    },
    description: "حال‌وهوای جنگل و آتش اردو، چوبی و دلنشین.",
  },
  {
    slug: "le-labo-santal-33",
    name: "سانتال ۳۳",
    brand: "لو لابو",
    gender: "unisex",
    releaseYear: 2011,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 4,
    projection: 3,
    sweetness: 1,
    freshness: 2,
    seasons: ["autumn", "winter", "spring"],
    occasions: ["daily", "office"],
    scentFamilies: ["woody", "leather", "smoky"],
    notes: {
      top: ["هل", "زنبق", "بنفشه"],
      middle: ["صندل", "کاغذ پاپیروس"],
      base: ["چرم", "عنبر", "سدر"],
    },
    description: "صندل چرمی و دودی با شخصیتی مستقل و متفاوت.",
  },
  {
    slug: "margiela-by-the-fireplace",
    name: "بای د فایرپلیس",
    brand: "مزون مارژیلا",
    gender: "unisex",
    releaseYear: 2015,
    concentration: "EDT",
    priceRange: "mid",
    longevity: 3,
    projection: 3,
    sweetness: 4,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["casual", "date"],
    scentFamilies: ["smoky", "woody", "gourmand"],
    notes: {
      top: ["فلفل صورتی", "پرتقال"],
      middle: ["شاه‌بلوط", "گل‌ لاک"],
      base: ["وانیل", "چوب گایاک", "کاشمیر"],
    },
    description: "بوی شومینه و شاه‌بلوط برشته؛ دودی، گرم و صمیمی.",
  },
  {
    slug: "jo-malone-wood-sage-sea-salt",
    name: "وود سیج اند سی سالت",
    brand: "جو مالون",
    gender: "unisex",
    releaseYear: 2014,
    concentration: "Cologne",
    priceRange: "luxury",
    longevity: 2,
    projection: 2,
    sweetness: 1,
    freshness: 5,
    seasons: ["spring", "summer"],
    occasions: ["daily", "casual"],
    scentFamilies: ["aquatic", "fresh", "woody"],
    notes: {
      top: ["مریم‌گلی", "آمبرت"],
      middle: ["نمک دریا"],
      base: ["جلبک", "گریپ‌فروت"],
    },
    description: "نسیم ساحل و صخره‌های دریا، سبک و شفاف.",
  },
  {
    slug: "guerlain-shalimar",
    name: "شالیمار",
    brand: "گرلن",
    gender: "women",
    releaseYear: 1925,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 4,
    projection: 3,
    sweetness: 4,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "date"],
    scentFamilies: ["amber", "vanilla", "citrus"],
    notes: {
      top: ["برگاموت", "لیمو"],
      middle: ["یاس", "رز", "زنبق"],
      base: ["وانیل", "بخور", "تونکا"],
    },
    description: "اسطوره عنبری-وانیلی؛ پرجزئیات و کلاسیک.",
  },
  {
    slug: "creed-silver-mountain-water",
    name: "سیلور مانتین واتر",
    brand: "کرید",
    gender: "men",
    releaseYear: 1995,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 3,
    projection: 3,
    sweetness: 1,
    freshness: 5,
    seasons: ["spring", "summer"],
    occasions: ["daily", "office"],
    scentFamilies: ["fresh", "citrus", "aquatic"],
    notes: {
      top: ["برگاموت", "ماندارین"],
      middle: ["چای سبز", "قره‌قاط"],
      base: ["مشک", "صندل"],
    },
    description: "چای سبز و برگاموت روی آب‌های کوهستانی، خنک و صاف.",
  },
  {
    slug: "amouage-interlude-man",
    name: "اینترلود من",
    brand: "آمواج",
    gender: "men",
    releaseYear: 2012,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 5,
    projection: 5,
    sweetness: 2,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening"],
    scentFamilies: ["smoky", "spicy", "amber"],
    notes: {
      top: ["برگاموت", "فلفل", "پرتقال"],
      middle: ["بخور", "مرزنجوش", "ادویه"],
      base: ["عنبر", "عود", "پچولی"],
    },
    description: "دودی و پرقدرت، شخصیتی پیچیده و پرغلظت.",
  },
  {
    slug: "xerjoff-naxos",
    name: "ناکسوس",
    brand: "زرجف",
    gender: "unisex",
    releaseYear: 2015,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 5,
    projection: 4,
    sweetness: 5,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "date"],
    scentFamilies: ["gourmand", "warm-spicy", "vanilla"],
    notes: {
      top: ["لیمو", "برگاموت", "اسطوخودوس"],
      middle: ["عسل", "دارچین", "یاس"],
      base: ["تنباکو", "وانیل", "تونکا"],
    },
    description: "عسل و تنباکوی شیرین و گرم، لوکس و پرجزئیات.",
  },
  {
    slug: "viktor-rolf-spicebomb",
    name: "اسپایس‌بمب",
    brand: "ویکتور اند رولف",
    gender: "men",
    releaseYear: 2012,
    concentration: "EDT",
    priceRange: "mid",
    longevity: 4,
    projection: 4,
    sweetness: 3,
    freshness: 2,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "casual"],
    scentFamilies: ["spicy", "warm-spicy", "leather"],
    notes: {
      top: ["فلفل صورتی", "گریپ‌فروت", "برگ بو"],
      middle: ["دارچین", "زعفران", "فلفل"],
      base: ["تنباکو", "چرم", "وانیل"],
    },
    description: "انفجار ادویه‌های گرم، قوی و جسور.",
  },
  {
    slug: "carolina-herrera-good-girl",
    name: "گود گرل",
    brand: "کارولینا هررا",
    gender: "women",
    releaseYear: 2016,
    concentration: "EDP",
    priceRange: "mid",
    longevity: 4,
    projection: 4,
    sweetness: 5,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "date"],
    scentFamilies: ["gourmand", "floral", "vanilla"],
    notes: {
      top: ["بادام", "قهوه"],
      middle: ["مریم", "یاس سامبک"],
      base: ["کاکائو", "تونکا", "وانیل"],
    },
    description: "ترکیب شیرین و گلی، جذاب و شیک برای شب.",
  },
  {
    slug: "narciso-rodriguez-for-her",
    name: "فور هر",
    brand: "نارسیسو رودریگز",
    gender: "women",
    releaseYear: 2003,
    concentration: "EDP",
    priceRange: "mid",
    longevity: 4,
    projection: 3,
    sweetness: 2,
    freshness: 2,
    seasons: ["autumn", "winter", "spring"],
    occasions: ["date", "office"],
    scentFamilies: ["musky", "floral", "powdery"],
    notes: {
      top: ["هلو", "برگاموت"],
      middle: ["گل رز", "عنبر"],
      base: ["مشک", "پچولی", "وانیل"],
    },
    description: "مشکی و حسی با گل‌های ظریف، نرم و ماندگار.",
  },
  {
    slug: "hermes-terre-dhermes",
    name: "ترد هرمس",
    brand: "هرمس",
    gender: "men",
    releaseYear: 2006,
    concentration: "EDT",
    priceRange: "mid",
    longevity: 4,
    projection: 3,
    sweetness: 1,
    freshness: 3,
    seasons: ["spring", "autumn"],
    occasions: ["office", "daily"],
    scentFamilies: ["woody", "citrus", "spicy"],
    notes: {
      top: ["پرتقال", "گریپ‌فروت"],
      middle: ["فلفل", "ژرانیوم", "گل سنگ"],
      base: ["وتیور", "سدر", "بنزوین"],
    },
    description: "مینرال و خاکی با مرکبات؛ متفاوت و با کلاس.",
  },
  {
    slug: "tom-ford-black-orchid",
    name: "بلک ارکید",
    brand: "تام فورد",
    gender: "unisex",
    releaseYear: 2006,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 5,
    projection: 4,
    sweetness: 4,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["evening", "date"],
    scentFamilies: ["floral", "gourmand", "woody"],
    notes: {
      top: ["ترافل", "یاس", "بلک‌کارنت"],
      middle: ["ارکیده", "ادویه"],
      base: ["شکلات", "وانیل", "پچولی"],
    },
    description: "تیره و پرغلظت با ارکیده، شکلات و ترافل.",
  },
  {
    slug: "prada-luna-rossa-carbon",
    name: "لونا روسا کربن",
    brand: "پرادا",
    gender: "men",
    releaseYear: 2017,
    concentration: "EDT",
    priceRange: "mid",
    longevity: 3,
    projection: 3,
    sweetness: 1,
    freshness: 5,
    seasons: ["spring", "summer"],
    occasions: ["daily", "office"],
    scentFamilies: ["fresh", "aromatic", "woody"],
    notes: {
      top: ["برگاموت", "اسطوخودوس"],
      middle: ["ریحان", "نعنا"],
      base: ["آمبروکسان", "پچولی"],
    },
    description: "تمیز، فلزی و خنک؛ برای هوای گرم و محیط کار.",
  },
  {
    slug: "azzaro-the-most-wanted",
    name: "د موست وانتد",
    brand: "آزارو",
    gender: "men",
    releaseYear: 2021,
    concentration: "EDP",
    priceRange: "mid",
    longevity: 4,
    projection: 4,
    sweetness: 5,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["date", "evening"],
    scentFamilies: ["gourmand", "spicy", "woody"],
    notes: {
      top: ["هل", "زنجبیل"],
      middle: ["تافی"],
      base: ["چوب‌ها", "آمبروکسان"],
    },
    description: "شیرین و کارامل‌مانند با زنجبیل و هل.",
  },
  {
    slug: "louis-vuitton-pacific-chill",
    name: "پسیفیک چیل",
    brand: "لویی ویتون",
    gender: "unisex",
    releaseYear: 2021,
    concentration: "EDP",
    priceRange: "luxury",
    longevity: 3,
    projection: 3,
    sweetness: 1,
    freshness: 5,
    seasons: ["spring", "summer"],
    occasions: ["daily", "casual"],
    scentFamilies: ["fresh", "citrus", "aquatic"],
    notes: {
      top: ["لیمو", "نعنا"],
      middle: ["زنجبیل", "گل‌ها"],
      base: ["مشک", "چوب"],
    },
    description: "نسیم اقیانوس آرام؛ مرکباتی و تازه. (نت‌ها تقریبی‌اند)",
  },
  {
    slug: "billie-eilish-eilish",
    name: "آیلیش",
    brand: "بیلی آیلیش",
    gender: "women",
    releaseYear: 2019,
    concentration: "EDP",
    priceRange: "budget",
    longevity: 3,
    projection: 3,
    sweetness: 5,
    freshness: 1,
    seasons: ["autumn", "winter"],
    occasions: ["casual", "date"],
    scentFamilies: ["gourmand", "vanilla", "musky"],
    notes: {
      top: ["مندرین", "گل‌ سرخ"],
      middle: ["شکوفه‌ها", "کارامل"],
      base: ["وانیل", "مشک", "صندل"],
    },
    description: "شیرین، نرم و پوستی با وانیل و مشک.",
  },
];

export const getPopularFragrances = (limit = 6) => fragrances.slice(0, limit);

export const getFragranceBySlug = (slug) =>
  fragrances.find((fragrance) => fragrance.slug === slug) || null;

export const getAllSlugs = () => fragrances.map((fragrance) => fragrance.slug);

export const getSimilarFragrances = (fragrance, limit = 3) =>
  fragrances
    .filter((item) => item.id !== fragrance.id)
    .map((item) => ({
      item,
      score: item.scentFamilies.filter((f) =>
        fragrance.scentFamilies.includes(f),
      ).length,
    }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(({ item }) => item);

const getSearchText = (f) =>
  normalize(
    [
      f.name,
      f.brand,
      f.slug.replace(/-/g, " "),
      ...f.notes.top,
      ...f.notes.middle,
      ...f.notes.base,
    ].join(" "),
  );

export const searchFragrances = ({ q, family, gender, season, sort } = {}) => {
  let result = [...fragrances];

  const tokens = tokenize(q);
  if (tokens.length > 0) {
    result = result.filter((f) => {
      const text = getSearchText(f);
      return tokens.every((token) => text.includes(token));
    });
  }

  if (family) result = result.filter((f) => f.scentFamilies.includes(family));
  if (gender) result = result.filter((f) => f.gender === gender);
  if (season) result = result.filter((f) => f.seasons.includes(season));

  if (sort === "longevity") result.sort((a, b) => b.longevity - a.longevity);
  if (sort === "newest") result.sort((a, b) => b.releaseYear - a.releaseYear);

  return result;
};
export const getFragrancesBySlugs = (slugs = []) =>
  [...new Set(slugs)].map(getFragranceBySlug).filter(Boolean);


export const fragrances = data.map((f, i) => ({ id: i + 1, image: null, ...f }))
